using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;
using UnityEngine;

namespace DynamicProperty
{
    /// <summary>
    /// Sparse storage for dynamic properties.
    ///
    /// Each property ID may exist in exactly one storage bin:
    /// - 32-bit storage for int, float, bool and supported enums.
    /// - 64-bit storage for long, double, DateTime and TimeSpan.
    ///
    /// Typed public APIs are expected to be generated by the
    /// DynamicProperty source generator.
    /// </summary>
    [Serializable]
    public sealed partial class PropertySet : ISerializationCallbackReceiver
    {
        [SerializeField] private List<DynamicProperty32> _items32 = new();
        [SerializeField] private List<DynamicProperty64> _items64 = new();

        [NonSerialized] private Dictionary<int, int> _index32;
        [NonSerialized] private Dictionary<int, int> _index64;

        [NonSerialized] private HashSet<int> _conflictingIds;

        [NonSerialized] private bool _indexed;

        [SerializeField, HideInInspector] private int _structureVersion;

        [NonSerialized] private int _indexedStructureVersion;
        [NonSerialized] private int _indexedCount32;
        [NonSerialized] private int _indexedCount64;

        public void OnBeforeSerialize() { }
        public void OnAfterDeserialize() => RebuildIndex();

        /// <summary>
        /// Rebuilds runtime lookup indexes and detects corrupted
        /// serialized states without throwing during deserialization.
        /// </summary>
        public void RebuildIndex()
        {
            _index32 = new Dictionary<int, int>(_items32.Count);
            _index64 = new Dictionary<int, int>(_items64.Count);
            _conflictingIds = new HashSet<int>();

            // First occurrence wins deterministically.
            // Additional occurrences are marked as conflicts.
            for (int i = 0; i < _items32.Count; i++)
            {
                int id = _items32[i].Id;

                if (_index32.ContainsKey(id))
                {
                    _conflictingIds.Add(id);
                    continue;
                }

                _index32[id] = i;
            }

            for (int i = 0; i < _items64.Count; i++)
            {
                int id = _items64[i].Id;

                if (_index64.ContainsKey(id))
                {
                    _conflictingIds.Add(id);
                    continue;
                }

                _index64[id] = i;
            }

            // Detect IDs present in both storage bins.
            foreach (var id in _index32.Keys)
            {
                if (_index64.ContainsKey(id))
                    _conflictingIds.Add(id);
            }

            _indexedStructureVersion = _structureVersion;
            _indexedCount32 = _items32.Count;
            _indexedCount64 = _items64.Count;
            _indexed = true;
        }
        private void EnsureIndex()
        {
            if (!_indexed ||
                _index32 == null ||
                _index64 == null ||
                _conflictingIds == null ||
                _indexedStructureVersion != _structureVersion ||
                _indexedCount32 != _items32.Count ||
                _indexedCount64 != _items64.Count)
            {
                RebuildIndex();
            }
        }

        private void EnsurePropertyCanBeMutated(int id)
        {
            EnsureIndex();

            if (_conflictingIds.Contains(id))
            {
                throw new InvalidOperationException(
                    $"Dynamic property ID '{id}' has conflicting serialized entries. " +
                    "Remove or repair the property before modifying it.");
            }
        }

        private void EnsureNotIn64BitStorage(int id)
        {
            if (_index64.ContainsKey(id))
            {
                throw new InvalidOperationException(
                    $"Dynamic property ID '{id}' already exists in 64-bit storage " +
                    "and cannot be written as a 32-bit property.");
            }
        }

        private void EnsureNotIn32BitStorage(int id)
        {
            if (_index32.ContainsKey(id))
            {
                throw new InvalidOperationException(
                    $"Dynamic property ID '{id}' already exists in 32-bit storage " +
                    "and cannot be written as a 64-bit property.");
            }
        }

        #region Presence

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool Contains32(int id)
        {
            EnsureIndex();
            return _index32.ContainsKey(id);
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool Contains64(int id)
        {
            EnsureIndex();
            return _index64.ContainsKey(id);
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool ContainsAny(int id)
        {
            EnsureIndex();

            return _index32.ContainsKey(id) ||
                   _index64.ContainsKey(id);
        }
        
        #endregion

        #region Getters (32)
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetInt(int id, out int value)
        {
            EnsureIndex();

            if (_index32.TryGetValue(id, out int index))
            {
                value = _items32[index].GetInt();
                return true;
            }

            value = default;
            return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetFloat(int id, out float value)
        {
            EnsureIndex();

            if (_index32.TryGetValue(id, out int index))
            {
                value = _items32[index].GetFloat();
                return true;
            }

            value = default;
            return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetBool(int id, out bool value)
        {
            EnsureIndex();

            if (_index32.TryGetValue(id, out int index))
            {
                value = _items32[index].GetBool();
                return true;
            }

            value = default;
            return false;
        }

        #endregion

        #region Getters (64)
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetLong(int id, out long value)
        {
            EnsureIndex();

            if (_index64.TryGetValue(id, out int index))
            {
                value = _items64[index].GetLong();
                return true;
            }

            value = default;
            return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetDouble(int id, out double value)
        {
            EnsureIndex();

            if (_index64.TryGetValue(id, out int index))
            {
                value = _items64[index].GetDouble();
                return true;
            }

            value = default;
            return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetUtcDateTime(int id, out DateTime value)
        {
            EnsureIndex();

            if (!_index64.TryGetValue(id, out int index))
            {
                value = default;
                return false;
            }

            long ticks = _items64[index].RawValue;

            if (ticks < DateTime.MinValue.Ticks ||
                ticks > DateTime.MaxValue.Ticks)
            {
                value = default;
                return false;
            }

            value = new DateTime(ticks, DateTimeKind.Utc);

            return true;
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetTimeSpan(int id, out TimeSpan value)
        {
            EnsureIndex();

            if (_index64.TryGetValue(id, out int index))
            {
                value = _items64[index].GetTimeSpanTicks();
                return true;
            }

            value = default;
            return false;
        }

        #endregion

        #region Setters (32)

        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetInt(int id, int value)
        {
            UpsertRaw32(id, value);
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetFloat(int id, float value)
        {
            var raw = new ValueUnion32
            {
                asFloat = value
            }.raw;

            UpsertRaw32(id, raw);
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetBool(int id, bool value)
        {
            // Store bool canonically as 0 / 1.
            UpsertRaw32(id, value ? 1 : 0);
        }

        #endregion

        #region Setters (64)

        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetLong(int id, long value)
        {
            UpsertRaw64(id, value);
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetDouble(int id, double value)
        {
            var raw = new ValueUnion64
            {
                asDouble = value
            }.raw;

            UpsertRaw64(id, raw);
        }

        /// <summary>
        /// Stores an absolute UTC date/time.
        /// Local and Unspecified DateTime values are not accepted.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetUtcDateTime(int id, DateTime value)
        {
            if (value.Kind != DateTimeKind.Utc)
            {
                throw new ArgumentException(
                    "DynamicProperty DateTime values must use DateTimeKind.Utc.",
                    nameof(value));
            }

            UpsertRaw64(id, value.Ticks);
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetTimeSpan(int id, TimeSpan value)
        {
            UpsertRaw64(id, value.Ticks);
        }

        #endregion

        #region Enums

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TryGetEnum<TEnum>(int id, out TEnum value) 
            where TEnum : struct, Enum
        {
            EnsureIndex();

            if (EnumBitUtility.Uses64BitStorage<TEnum>())
            {
                if (_index64.TryGetValue(id, out int index))
                {
                    value = EnumBitUtility.FromRaw64<TEnum>(_items64[index].RawValue);

                    return true;
                }
            }
            else
            {
                if (_index32.TryGetValue(id, out int index))
                {
                    value = EnumBitUtility.FromRaw32<TEnum>(_items32[index].RawValue);

                    return true;
                }
            }

            value = default;
            return false;
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public void SetEnum<TEnum>(int id, TEnum value) 
            where TEnum : struct, Enum
        {
            if (EnumBitUtility.Uses64BitStorage<TEnum>())
            {
                UpsertRaw64(id, EnumBitUtility.ToRaw64(value));
            }
            else
            {
                UpsertRaw32(id, EnumBitUtility.ToRaw32(value));
            }
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool HasEnumFlag<TEnum>(int id, TEnum flag) 
            where TEnum : struct, Enum
        {
            if (!TryGetEnum<TEnum>(id, out var value))
            {
                return false;
            }

            return EnumBitUtility.HasFlag(value, flag);
        }

        #endregion

        #region Remove / Clear

        public bool Remove(int id)
        {
            EnsureIndex();

            bool removed = false;

            // Remove all occurrences so Remove can also repair
            // duplicated/corrupted serialized data.
            for (int i = _items32.Count - 1; i >= 0; i--)
            {
                if (_items32[i].Id != id)
                    continue;

                _items32.RemoveAt(i);
                removed = true;
            }

            for (int i = _items64.Count - 1; i >= 0; i--)
            {
                if (_items64[i].Id != id)
                    continue;

                _items64.RemoveAt(i);
                removed = true;
            }

            if (removed)
                RebuildIndex();

            return removed;
        }

        public void Clear()
        {
            _items32.Clear();
            _items64.Clear();

            _index32?.Clear();
            _index64?.Clear();
            _conflictingIds?.Clear();

            _indexedCount32 = 0;
            _indexedCount64 = 0;
            _indexedStructureVersion = _structureVersion;
            _indexed = true;
        }

        #endregion

        #region Tooling / diagnostics views

        internal IReadOnlyList<DynamicProperty32> Raw32 => _items32;

        internal IReadOnlyList<DynamicProperty64> Raw64 => _items64;

        internal bool HasStorageConflicts
        {
            get
            {
                EnsureIndex();
                return _conflictingIds.Count != 0;
            }
        }

        internal bool HasStorageConflict(int id)
        {
            EnsureIndex();
            return _conflictingIds.Contains(id);
        }

        #endregion

        #region Internal storage mutation

        private void UpsertRaw32(int id, int rawValue)
        {
            EnsurePropertyCanBeMutated(id);
            EnsureNotIn64BitStorage(id);

            if (_index32.TryGetValue(id, out int index))
            {
                var property = _items32[index];
                property.RawValue = rawValue;
                _items32[index] = property;
                return;
            }

            var newProperty = new DynamicProperty32(id)
            {
                RawValue = rawValue
            };

            _items32.Add(newProperty);
            _index32[id] = _items32.Count - 1;
            _indexedCount32 = _items32.Count;
        }

        private void UpsertRaw64(int id, long rawValue)
        {
            EnsurePropertyCanBeMutated(id);
            EnsureNotIn32BitStorage(id);

            if (_index64.TryGetValue(id, out int index))
            {
                var property = _items64[index];
                property.RawValue = rawValue;
                _items64[index] = property;
                return;
            }

            var newProperty = new DynamicProperty64(id)
            {
                RawValue = rawValue
            };

            _items64.Add(newProperty);
            _index64[id] = _items64.Count - 1;
            _indexedCount64 = _items64.Count;
        }

        #endregion

        public override string ToString()
        {
            var sb = new StringBuilder();

            sb.AppendLine("PropertySet:");

            if (_items32 == null || _items32.Count == 0)
            {
                sb.AppendLine("  [32] (none)");
            }
            else
            {
                sb.AppendLine("  [32]");

                foreach (var property in _items32)
                {
                    sb.AppendLine($"    - id {property.Id}: raw {property.RawValue}");
                }
            }

            if (_items64 == null || _items64.Count == 0)
            {
                sb.AppendLine("  [64] (none)");
            }
            else
            {
                sb.AppendLine("  [64]");

                foreach (var property in _items64)
                {
                    sb.AppendLine($"    - id {property.Id}: raw {property.RawValue}");
                }
            }

            return sb.ToString();
        }
    }
}
