// PropertySetExtensionsGenerator.cs
// <auto-generated> Generates extension methods for DynamicProperty.PropertySetView<TSchema> based on typed schema interfaces. </auto-generated>
using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace DynamicProperty.SourceGen
{
    [Generator]
    public sealed class PropertySetExtensionsGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SchemaSyntaxReceiver());
        }

        private static readonly DiagnosticDescriptor GeneratorFailure =
            new DiagnosticDescriptor(
                id: "DP0001",
                title: "DynamicProperty generator failed",
                messageFormat: "{0}",
                category: "DynamicProperty.SourceGen",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true);

        public void Execute(GeneratorExecutionContext context)
        {
            try
            {
                var compilation = context.Compilation;

                if (!GeneratorSymbols.TryCreate(compilation, out var symbols, out _))
                {
                    return;
                }

                if (!(context.SyntaxReceiver is SchemaSyntaxReceiver receiver))
                    return;

                var schemas =
                    SchemaDiscovery.Discover(compilation, receiver, symbols);

                if (schemas.Count == 0)
                    return;

                foreach (var schemaSymbol in schemas)
                {
                    var schema = SchemaParser.Parse(schemaSymbol, symbols, context.ReportDiagnostic);

                    if (schema.Properties.Count == 0)
                        continue;

                    if (!SchemaValidator.Validate(schema, context.ReportDiagnostic))
                        continue;

                    bool generatedNamesAreValid = GeneratedNameValidator.Validate(schema, context.ReportDiagnostic);

                    if (!generatedNamesAreValid)
                        continue;

                    var sb = new StringBuilder(16 * 1024);
                    var ns = schema.Namespace ?? "Global";
                    var extensionsClassName =
                        SourceNameUtility.GetExtensionClassName(schema);

                    sb.AppendLine("// <auto-generated/>");
                    sb.AppendLine("using System;");
                    sb.AppendLine("using DynamicProperty;");
                    sb.AppendLine();

                    if (ns != "Global")
                    {
                        sb.Append("namespace ").Append(ns).AppendLine();
                        sb.AppendLine("{");
                    }

                    sb.Append("    public static class ").Append(extensionsClassName).AppendLine();
                    sb.AppendLine("    {");

                    bool emittedAny = false;

                    foreach (var property in schema.Properties)
                    {
                        string generatedPropertyName = IdentifierUtility.ToPascalIdentifier(property.Name);

                        if (property.AggregateKind == AggregateKind.None)
                        {
                            ScalarEmitter.Emit(sb, schema, property, generatedPropertyName);
                        }
                        else
                        {
                            AggregateEmitter.Emit(sb, schema, property, generatedPropertyName);
                        }

                        emittedAny = true;

                        if (property.AggregateKind == AggregateKind.None &&
                            property.Kind == ValueKind.Enum &&
                            property.IsFlagsEnum)
                        {
                            EmitFlagChecksForProperty(
                                sb,
                                schema,
                                property.DeclaredType,
                                AggregateContract.GetStorageIdExpression(property.LogicalId, 0),
                                generatedPropertyName);

                            emittedAny = true;
                        }
                    }

                    sb.AppendLine("    }");

                    if (ns != "Global")
                        sb.AppendLine("}");

                    if (emittedAny)
                        context.AddSource(SourceNameUtility.GetHintName(schema), sb.ToString());
                }
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(GeneratorFailure, Location.None, ex.ToString()));
            }
        }

        // ---------- [Flags] helpers ----------

        private static void EmitFlagChecksForProperty(
            StringBuilder sb,
            SchemaModel schema,
            ITypeSymbol enumType,
            string idExpr,
            string owningPropertyName)
        {
            string enumFqn = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string receiverType =
                GeneratorTypeUtility.GetPropertySetViewType(schema);

            foreach (var flagField in
                     enumType
                         .GetMembers()
                         .OfType<IFieldSymbol>())
            {
                if (!flagField.HasConstantValue)
                    continue;

                string methodName = IdentifierUtility.GetFlagMethodName(owningPropertyName, flagField.Name);

                string enumMemberName = IdentifierUtility.EscapeIdentifier(flagField.Name);

                sb.Append("        public static bool ")
                    .Append(methodName)
                    .Append("(this ")
                    .Append(receiverType)
                    .Append(" view)")
                    .AppendLine();

                sb.AppendLine("        {");

                sb.Append("            return view.PropertySet.HasEnumFlag(")
                    .Append(idExpr)
                    .Append(", ")
                    .Append(enumFqn)
                    .Append('.')
                    .Append(enumMemberName)
                    .AppendLine(");");

                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }
    }
}
